awslabs/harmonix

backstage-reference/templates/example-serverless-rest-api/skeleton/template.yml, infrastructure/src/constructs/role-construct.ts
Deployment failures occur for SAM-based serverless applications.  Permissions required for the backstage-* roles need to be updated per documentation at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-permissions-cloudformation.html.
=> fix: deployment permission errors for SAM apps

backstage-plugins/plugins/aws-apps-backend/package.json, backstage-plugins/plugins/aws-apps-common/package.json, backstage-plugins/plugins/aws-apps-demo/package.json, backstage-plugins/plugins/aws-apps/package.json, backstage-plugins/plugins/package.json, backstage-plugins/plugins/scaffolder-backend-module-aws-apps/package.json, scripts/backstage-install.sh
=> Update npm packages

README.md
Add YouTube playlist link to README.md
=> Add YouTube playlist link to README.md

backstage-plugins/plugins/aws-apps-backend/LICENSE, backstage-plugins/plugins/aws-apps-common/LICENSE, backstage-plugins/plugins/aws-apps-demo/LICENSE, backstage-plugins/plugins/aws-apps/LICENSE, backstage-plugins/plugins/scaffolder-backend-module-aws-apps/LICENSE, scripts/npm-publish.sh
=> updating license and npm publication

backstage-reference/templates/example-serverless-rest-api/skeleton/.gitlab-ci.yml
=> fix python issue in serverless gitlab pipeline

infrastructure/README.md
=> Update Documentation for issue #18

Makefile, backstage-reference/common/aws_rds/src/cdk-rds-module-stack.ts, build-script/destroy-platform.sh, build-script/set-gitlab-token.sh
fixes install script errors
ensures encryption for sample template to create RDS resource
=> Install platform issues

iac/roots/opa-platform/src/opa-platform-stack.ts
=> fix: prevent blank strings in allowed ips array

build-script/gitlab-tools.sh
*Description of changes:* fix: git-defender detection in gitlab-tools script
=> fix: git-defender detection in gitlab-tools script

backstage-reference/common/cicd/scripts/example-tf-nodejs/create-ci-stages.sh
fix TF bucket and table name to lower case
=> fix TF long name to shorter name

backstage-reference/common/cicd/scripts/example-tf-nodejs/create-ci-stages.sh, iac/roots/opa-common-constructs/package.json, iac/roots/opa-ecs-environment/package.json, iac/roots/opa-platform/package.json, iac/roots/opa-serverless-environment/package.json
=> Npm private package

iac/roots/opa-common-constructs/package.json, iac/roots/opa-ecs-environment/package.json, iac/roots/opa-ecs-environment/src/constructs/ecs-env-operations-role-construct.ts, iac/roots/opa-ecs-environment/src/constructs/ecs-env-provisioning-role-construct.ts, iac/roots/opa-ecs-environment/src/opa-ecs-env-app.ts, iac/roots/opa-ecs-environment/src/opa-ecs-environment-stack.ts, iac/roots/opa-platform/package.json, iac/roots/opa-platform/src/constructs/backstage-fargate-service-construct.ts, iac/roots/opa-platform/src/constructs/gitlab-hosting-construct.ts, iac/roots/opa-platform/src/constructs/gitlab-runner-construct.ts, iac/roots/opa-platform/src/constructs/opa-role-construct.ts, iac/roots/opa-platform/src/opa-platform-stack.ts, iac/roots/opa-serverless-environment/package.json, iac/roots/opa-serverless-environment/src/constructs/serverless-api-env-operations-role-construct.ts, iac/roots/opa-serverless-environment/src/constructs/serverless-api-env-provisioning-role-construct.ts, iac/roots/opa-serverless-environment/src/opa-serverless-env-app.ts, iac/roots/opa-serverless-environment/src/opa-serverless-environment-stack.ts, iac/roots/yarn.lock
update package names for aws namespace
=> fix: update packages to aws namespace

backstage-plugins/plugins/aws-apps/src/hooks/useAwsApp.tsx, backstage-plugins/plugins/aws-apps/src/pages/AwsAppPage/AwsAppPage.tsx
fix: error switching the current environment in UI if environment name contains capital letters. Also improve logging in the UI when the current environment cannot be set successfully. This logging will make it much easier to debug the issue.
=> fix: error switching the current environment in UI if environment name contains capital letters

website/package.json, website/src/components/HomepageFeatures.tsx, website/src/css/custom.css, website/src/pages/index.tsx, website/yarn.lock
🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.
=> coming soon

.github/workflows/makefile.yml, website/src/components/HomepageFeatures.tsx
🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.
=> Website docs

website/src/components/HomepageFeatures.tsx
🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.
=> change order

backstage-reference/common/cicd/.gitlab-ci-aws-provider-eks.yml
Fix #78
Replace the hard-coded value with a variable
The out-of-the box experience was not working
=> fix(existing-eks-prov-cicd): Replace the hard-coded region

backstage-plugins/plugins/scaffolder-backend-module-aws-apps/package.json, build-script/local-runners.sh, website/docs/faq.md, website/docs/techdocs/customizations.md
Add documentation to website for running Backstage locally
=> Running locally

backstage-reference/common/cicd/.gitlab-ci-aws-provider-eks.yml
fix to eks provider pipeline kubectl installation
=> fix: eks provider pipeline kubectl installation

backstage-plugins/plugins/aws-apps/src/plugin.ts
This PR exports all existing AWS app pages, making AWS-related pages more customizable
This is to resolve the following issue: https://github.com/awslabs/harmonix/issues/145
N/A
=> feat: export all AWS app pages

backstage-mods/backstage_0.6.1.diff.patch, backstage-plugins/plugins/harmonix-frontend/package.json, backstage-plugins/plugins/harmonix-frontend/src/demo/index.ts, backstage-plugins/plugins/harmonix-frontend/src/index.ts
🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/awslabs/data-on-eks/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.
=> bug fix homepage export
